export const proofUrl='https://github.com/plby/lean-proofs/blob/f06c4076c5352252d1dbab91ae3afa28037f466c/src/v4.24.0/ErdosProblems/Erdos728b.lean';
export const paperUrl='https://arxiv.org/html/2601.07421v5#S6';
export const stages=[
  {id:'middle',label:'Pick the middle',short:'Choose c',line:1386,code:"set c := (C + C') / 2 with hc_def",explanation:'C and C′ are the allowed limits. Their midpoint c sits safely between them.',result:'C < c < C′',evidence:[{line:1386,text:"set c := (C + C') / 2 with hc_def"},{line:1387,text:"have hc_bounds : C < c ∧ c < C' := by"},{line:1388,text:'constructor <;> linarith;'}]},
  {id:'scale',label:'Go far enough',short:'Choose M',line:1390,code:'obtain ⟨M, hM⟩',explanation:'Earlier lemmas each work beyond a threshold. The code chooses M beyond all five, so every required bound holds at once.',result:'M passes all five thresholds',evidence:[{line:1393,text:'lemma_k_val_lower_bound_eventually'},{line:1395,text:"lemma_k_val_lt_C'_log_pos"},{line:1397,text:'lemma_k_val_upper_bound_eventually'},{line:1399,text:'lemma_threshold_weak_uniform'},{line:1401,text:'lemma_good_m_exists_any_c'},{line:1402,text:'M1 + M2 + M3 + M4 + M5 + 2'}]},
  {id:'candidate',label:'Take a good candidate',short:'Choose m',line:1403,code:'obtain ⟨ m, hm ⟩ := hM.2.2.2.2.2;',explanation:'The earlier counting argument guarantees a candidate outside the failure set. obtain extracts that m together with the evidence hm.',result:'M ≤ m ≤ 2M, with the needed prime conditions',evidence:[{line:1403,text:'obtain ⟨ m, hm ⟩ := hM.2.2.2.2.2;'}]},
  {id:'witnesses',label:'Fill the three unknowns',short:'Set a, b, n',line:1404,code:'use m + k_val c M, m, 2 * m;',explanation:'use supplies the three numbers requested by ∃. Here k = floor(c log M), so the gap a + b − n is exactly k.',result:'a = m + k · b = m · n = 2m',evidence:[{line:1404,text:'use m + k_val c M, m, 2 * m;'}]},
  {id:'finish',label:'Supply every required fact',short:'Finish',line:1411,code:"refine' ⟨ by linarith, _, _, this.2.2.2.2.1, this.2.2.2.2.2, _ ⟩;",explanation:'The construction lemma supplies divisibility and other bounds. refine assembles the six facts; linarith and nlinarith close the remaining inequalities.',result:'The logarithmic-window existence claim is proved in the source.',evidence:[{line:1405,text:'lemma_good_triple_construction_final'},{line:1411,text:"refine' ⟨ by linarith, _, _, this.2.2.2.2.1, this.2.2.2.2.2, _ ⟩;"},{line:1412,text:'nlinarith'},{line:1413,text:'nlinarith'},{line:1414,text:'linarith'}]},
];
export const conditions=[['n > 0','A positive size'],['εn < a','a is not too small'],['εn < b','b is not too small'],['a! b! ∣ n! k!','Division leaves no remainder'],['C log n < k','Gap above the lower limit'],['k < C′ log n','Gap below the upper limit']];
